version: '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - .envs/.default/.postgres
  web_phuot:
    build:
      context: .
      dockerfile: ./docker/default/Dockerfile
    image: web_phuot
    container_name: web_phuot
    volumes:
      - .:/code/
    depends_on:
      - postgres
    env_file:
      - .envs/.default/.aws
      - .envs/.default/.firebase
    ports:
    - '80:80'
