version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: local_postgres
    restart: always
    container_name: local_postgres
    env_file:
      - .envs/.default/.postgres
#    volumes:
#      - local_postgres_data:/var/lib/postgresql/data:Z
#      - local_postgres_data_backups:/backups:z
  local_web_phuot:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    image: local_web_phuot
    container_name: local_web_phuot
    volumes:
      - .:/code/
    depends_on:
      - postgres
    env_file:
      - .envs/.default/.aws
      - .envs/.default/.firebase
      - .envs/.default/.postgres
    ports:
      - '80:80'
